### ISSUE TITLE
The Near Rectilinear Halo Orbit part of the map has errors

### ISSUE THREAD

**Issue by Moonwards** [deltavmap/deltavmap.github.io#4]
I love your map, but the part about the NRHO around the moon is wrong.

Your figures for transferring to that orbit and then entering it are for travel there from the Earth, not the moon.
Here's a reference for that - http://newpapyrusmagazine.blogspot.com/2018/06/cis-lunar-gateways-and-advantages-of.html

And a paper on NASA's NTRS server that talks about it in detail - https://ntrs.nasa.gov/citations/20150019648

The numbers didn't look right so I checked. I can't do the math, so I hope those refs are enough for you to work from. Looks like you'll need to draw a line from Earth to the NRHO circle and put NRHO transfer on that line, and leave the line between NRHO and LLO.

**Comment by deltavmap** [comment]
Thanks for this 👍 I'll look into it.

**Comment by deltavmap** [comment]
You're right. The NRHO numbers were off. I've removed the NRHO Transfer orbit and I've added an edge from Moon Transfer to NRHO. The numbers seem better now. If this looks good to you I'll close this issue.

**Comment by Moonwards** [comment]
Sorry, I only just saw this.

I'm not sure those figures are right. I'm going to recommend something I should have thought of before - ask on the [Space Exploration Stack Exchange](https://space.stackexchange.com/)
They will definitely give you a very well informed, precise answer.

**Comment by Moonwards** [comment]
Another thing, actually - there was this Tweet under the Tweet from ToughSF that caused me to find this map, and I copied the text because I wanted to ask on the Space Exploration SE if it was true, but I bet it is. 

"Unfortunately it's not correct. It merely sums all the intervening delta-v's, but it you are doing a single transfer burn to the target, you have to take the square-root of the sum of the squares of delta-v's. (In effect, summing the energy, converting back to delta-v.)"

Now, I'm actually kind of busy to get into asking about that, but I recommend that you do. If you were to incorporate that math into the final calculation of delta V, when dealing with destinations that would have that mechanism - where you do one burn to move from the one orbit to the other, not a chain of them like the map shows - then you would instantly have the King of all Delta V maps.

**Comment by deltavmap** [comment]
Hi Moonwards, thanks for this. You're correct, the deltav number incorrectly includes the insertion burn delta v for every node along the path. I'll work on a solution.
